spring:
  application:
    name: p-p-backend
  datasource:
    url: jdbc:mysql://localhost:3306/pp-portal?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true